### PR TITLE
Change it so that every time the window becomes visible a reload is forced 

### PR DESCRIPTION
**Pull request by peteryongzhong**
…rced

### CODE REVIEW

**Comment by peteryongzhong** [comment]
Addressing https://github.com/filibuster-testing/filibuster-intellij-webview-plugin/issues/4

**Comment by peteryongzhong** [comment]
For #4, there was a slight delay(1s) in reloading the page. This addresses that delay.

**Comment by cmeiklejohn-dd** [comment]
This good to go -- can I merge and package?  (e.g., did you successfully reproduce the problem and verify the fix works?)

**Comment by peteryongzhong** [comment]
On my side, I was able to reproduce that when the window is hidden in between tests there is a 1s window where the old tests were still showing. However, after that it refreshes. Is this behavior the same as yours?

**Comment by cmeiklejohn** [comment]
For me:

* I run a test, it finishes.  The test window is open.
* I close it.
* I run a test, it finishes.
* I open it, it's got the old results and never refreshes no matter how long I wait, because no files change.

**Comment by peteryongzhong** [comment]
Ah I see. I was able to reproduce this. And can confirm this PR fixes it.

**Review by cmeiklejohn-dd — APPROVED** [review]

**Review by cmeiklejohn — APPROVED** [review]

**Comment by cmeiklejohn** [comment]
Published 0.1.5 to the marketplace.

**Pull request merged**
